# Generated by Django 4.0.3 on 2022-04-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_comentarios_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
