# Generated by Django 4.0.3 on 2022-04-28 20:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_comentarios_usuario_alter_posts_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
