# Generated by Django 4.0.3 on 2022-05-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_posts_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='subtitulo',
            field=models.CharField(max_length=400),
        ),
    ]
