# Generated by Django 4.0.3 on 2022-04-28 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='emisor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
