# Generated by Django 4.0.3 on 2022-04-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_alter_mensajes_emisor_alter_mensajes_receptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='fechap',
            field=models.DateTimeField(default=None),
        ),
    ]
